export const GET_INITIAL_RESULTS_DATA = 'GET_INITIAL_RESULTS_DATA'; 
export const GET_INITIAL_SAVED_PROPERTIES_DATA = 'GET_INITIAL_SAVED_PROPERTIES_DATA';
export const ADD_TO_SAVED = 'ADD_TO_SAVE'; 
export const REMOVE_FROM_SAVED = 'REMOVE_FROM_SAVE';